sudo: required
dist: trusty

language: generic
os:
  - linux

install:
  - nvm use node
  - npm install lix@15.0.0-rc.8 -g
  - lix download

script:
  - lix run travix interp
  - lix run travix neko
  - lix run travix node
  - lix run travix python
  - lix run travix java
